spring.application.name=gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8760/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.routes[0].id=ms-clientes
spring.cloud.gateway.routes[0].uri=lb://ms-clientes
spring.cloud.gateway.routes[0].predicates[0]=Path=/clientes/**

spring.cloud.gateway.routes[1].id=ms-autos
spring.cloud.gateway.routes[1].uri=lb://ms-autos
spring.cloud.gateway.routes[1].predicates[0]=Path=/autos/**

spring.cloud.gateway.routes[2].id=ms-ventas
spring.cloud.gateway.routes[2].uri=lb://ms-ventas
spring.cloud.gateway.routes[2].predicates[0]=Path=/ventas/**

spring.cloud.gateway.routes[3].id=ms-auth
spring.cloud.gateway.routes[3].uri=lb://ms-auth
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

















