spring.application.name=ms-auth

server.port=8088

eureka.client.service-url.defaultZone=http://localhost:8760/eureka

jwt.secret=MiClaveSuperSeguraParaJWT2026SpringBoot
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


