spring.application.name=ms-autos
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8760/eureka


spring.datasource.url=jdbc:postgresql://localhost:5432/autos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#este es un comentario para github